version: '3'
services:
  db:
    image: postgres:11-alpine
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"
      TZ: "${TZ}"
    volumes:
      - ./database:/var/lib/postgresql/data
